### ISSUE TITLE
Extend Hazelcast Split-Brain Protection

### ISSUE THREAD

**Issue by tombujok** [hazelcast/hazelcast#11876]
Done in 3.10
- [x] ISet (#11869)
- [x] TransactionalSet (#12007)
- [x] IList (#11869)
- [x] TransactionalList (#12007)
- [x] ISemaphore (#11874)
- [x] ICountDownLatch (#12063)
- [x] IReplicatedMap (#11936)
- [x] IAtomicLong (#12045)
- [x] IExecutorService (#12020)
- [x] IDurableExecutorService (#12020)
- [x] IScheduledExecutorService (#12020)
- [x] IMultiMap (#11994)
- [x] TransactionalMultiMap (#11994)
- [x] IRingBuffer (#12024)
- [x] CardinalityEstimator (#12031)
- [x] IAtomicReference (#12045)

Done prior to 3.10 but refactored in 3.10:
- [x] IMap
- [x] TransactionalMap
- [x] ICache
- [x] ILock
- [x] IQueue
- [x] TransactionalQueue

Tasks, fixes & issues:
- [x] Refactor tests for TransactionalMap (#11936)
- [x] IAtomicLong, AtomicReference have no Config class (#11910)
- [x] What with methods like localKeySet, or replicateMap where the data are local anyway? 
- [x] Add tests for transactional structures (#12007)
- [x] ICountDownLatch has no Config class (#12062)
- [x] Migrate tests of ICache, ILock, IMap & IQueue to the new testing framework (#12068)
- [x] Add quorum to all missing configs (xsd, sprint, etc.) (#12112)
- [x] Disable quorum for new structures in clusterVersion < 3.10 (#12085)
- [x] Eliminate config cache memory leak (#12085)
- [x] Add javadoc info about quorum support in each structure (#12085)
- [x] check copy-paste errors in setQuorum read only methods (#12085)
- [x] Check if MergeOperation are not marked as MutatingOperations in all structures (#12088)
- [x] Delete unnecessary HD tests, Refactor HD tests (#https://github.com/hazelcast/hazelcast-enterprise/pull/1847)
- [x] Make IMap's and ICache's MergeOperation not implement MutatingOperation (#12089)
- [x] Removing redundancy in quorum tests (#12085)
- [x] Rolling Upgrade tests (#12085)
- [x] Client compatibility (serialization & client-protocol) (https://github.com/hazelcast/hazelcast-client-protocol/pull/111, #12127)
- [x] Review old & new structures for proper MutatingOperation & ReadOnlyOperation handling  (#12089, #12134, https://github.com/hazelcast/hazelcast-enterprise/pull/1863)
- [x] Add an explanation what quorum means in javadoc. Change the exception message. (#12136)
- [x] Update samples (https://github.com/hazelcast/hazelcast-code-samples/pull/211)
- [x] Update ref-manual (https://github.com/hazelcast/hazelcast-reference-manual/pull/477)
- [x] Update TDD
  
Close when all following PRs have been merged:
https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+author%3Atombujok+quorum
