### ISSUE TITLE
Add Java 9+ support (modularization)

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#13182]
Improve user experience on newer Java versions 9+ which are based on Java Platform Module System

- [x] make a clear package separation between members and clients
  - [x] #13273 
  - [x] hazelcast/hazelcast-enterprise#2184
- [x] introduce 2 new automatic modules `com.hazelcast` and `com.hazelcast.client` (The hazelcast-all and hazelcast-enterprise-all JARs will not be modularized.)
  - [x] #13319
  - [x] hazelcast/hazelcast-enterprise#2196
- [x] upgrade PowerMock and Mockito in testsuites
  - [x] #13352
  - [x] hazelcast/hazelcast-enterprise#2207
  - [x] workaround XML parser classloading issue powermock/powermock#864 by using `--add-exports java.xml/jdk.xml.internal=ALL-UNNAMED` argument
    - [x] fix included in the HotRestart fix - hazelcast/hazelcast-enterprise#2206
    - [x] fix included in new modulepath tests - #13443
- [x] fix failing tests with Java 9
  - [x] hazelcast/hazelcast#13440 `StackTraceElement` introduced new fields in Java 9 - we have to align comparison after applying `decode(encode(element))`
  - [x] OSGi test issue - `HazelcastOSGiIntegrationTest` uses a legacy version of PaxExam. It's not able to work properly with Java 9+. The upgrade is not straight forward as the originally used embedded OSGi container is not part of new PaxExam versions anymore. Workaround: #13535 
- [x] fix failing tests with Java 10
  - [x] upgrade failsafe Maven plugin to resolve an NPE #13545 
- [x] resolve problems which come with using internal Java APIs
  - [x] hazelcast/hazelcast-enterprise#2206 explicit cleanup of `MappedByteBuffer/DirectByteBuffer` in hot-restart code `GcHelper`
  - [x]  #13549 , #13567 OS level metrics (issue #13463)
- [x] document configuration requirements for Java 9  (hazelcast/hazelcast-reference-manual#585)
  - [x] `WARNING: An illegal reflective access operation has occurred`
    - [x] `SelectorOptimizer` as reported in #13151
    - [x] `MmapSlab` as reported in hazelcast/hazelcast-enterprise#875
    - [x] `TimedMemberStateFactoryHelper` accessing `sun.management.BaseOperatingSystemImpl.getAvailableProcessors()`
  - [x] requirements for HotRestart feature
- [x] add modulepath tests
  - [x] OS #13443
  - [x] EE hazelcast/hazelcast-enterprise#2273
    - [x] hot restart: hazelcast/hazelcast-enterprise#2313
  - [x] run the new modulepath tests withinin PR builder jobs (EE & OS)
- [x] resolve the `WARNING: Illegal reflective access by ...` by explicit opening packages
  - [x] OS #13592 
  - [x] EE hazelcast/hazelcast-enterprise#2313
- [x] fix code samples to compile with Java 9 and newer: hazelcast/hazelcast-code-samples#256
- [x] fix EE test compile issue on Java 11 hazelcast/hazelcast-enterprise#2313
- [x] add a smoke test for TLS 1.3 in Java 11 hazelcast/hazelcast-enterprise#2384
- [x] add a warning when the access to required Java internal packages is not provided #13809

Prototype of resolving public API class in overlapping packages:
https://github.com/sancar/hazelcast/tree/ench/aSmallStepForModulariozation

Related issues:
- [x] hazelcast/hazelcast#13151
- [x] hazelcast/hazelcast#13463 OS level metrics - fixed by #13549
- [x] hazelcast/hazelcast-enterprise#875

**Comment by mmedenjak** [comment]
@kwart can we close this issue? Is there anything left?

**Comment by kwart** [comment]
Yes I'll close this one :+1:

**Comment by ade90036** [comment]
Well done 🏇. I was waiting for the JDK 9+ support to be completed so I could test it against my app and JDK 11 (long term release) now GA.

**Comment by kwart** [comment]
Yes, these changes are included in the 3.11 release.

**Comment by ade90036** [comment]
Oh.. release.. already? Savage. 

Is the 3.11 release synched with the GitHub repo yet? 

Cause, I need to get the 3.11 source code as I have a custom extension which I need to check if it still works. 

Thanks.

**Comment by kwart** [comment]
Each released version has own tag in the repository. See https://github.com/hazelcast/hazelcast/tree/v3.11

**Comment by ade90036** [comment]
Thank you. :+1:

**Comment by ARSPRodrigo** [comment]
Hi,
What is the most stable version for Java 11?
Thanks.

**Comment by kwart** [comment]
> What is the most stable version for Java 11?

The most recent Hazelcast version is 3.12.1. The version 3.12.2 will be released in the near future.
